### ISSUE TITLE
Only 1 video in tktrex.htmls

### ISSUE THREAD

**Issue by rugantio** [tracking-exposed/tktrex#1]
On loading the homepage only 1 html snippet is retrieved and store in the mongodb htmls.

The behavior seems to be caused by the `handleVideo` function of app.js in the extension.

Below I attach a screenshot of the console response:
![image](https://user-images.githubusercontent.com/28983363/140538422-b73d83d7-572b-44eb-84be-aef05ef308f9.png)

**Comment by rugantio** [comment]
The relevant part of HTML:
![image](https://user-images.githubusercontent.com/28983363/140539098-757e0cfe-881c-4d23-82c1-510ca8ffe28f.png)

**Comment by vecna** [comment]
This is known, but it doesn't matter. one HTML at every access should provide you enough HTML to test the parser.

The issue you are reporting was present also during the hackathon, and it is due an incorrect usage of `MutationObserver`.

Also the HTML previously collected were taken with the same problem (one HTML per refresh).

**Comment by vecna** [comment]
Actually I can't reproduce the bug, 
![image](https://user-images.githubusercontent.com/89555/141137032-9984affa-8483-4efc-9a1b-77ecab144d39.png)
this is what happen on my local backend. more I scroll, and more video are reported.

can you copypaste your backend output? thanks

**Comment by rugantio** [comment]
I scrolled down but I don't see any feedback (events) reported in the shell:
![image](https://user-images.githubusercontent.com/28983363/141315821-6b185b08-632f-4949-83d2-2635a5aa5f85.png)

the chromium console says:
![image](https://user-images.githubusercontent.com/28983363/141316033-35285427-2413-4dd5-a40e-25f99ade713d.png)

**Comment by rugantio** [comment]
Could you check that your HTML structure is similar to the one I'm getting? (I'm using chromium) 
I tried with another tk account and I get the same only-1 result
