### ISSUE TITLE
HTML href and nature parser

### ISSUE THREAD

**Issue by rugantio** [tracking-exposed/tktrex#2]
The nature.js parser in the backend is parsing the URL according to the href in the tktrex/htmls table.
The only type of href that I have is "https://www.tiktok.com/" or single account pages: "https://www.tiktok.com/@edsheeran?lang=en"

1) we are missing href for "foryou, following, video"  
2) the href with the account result in "unmanaged condition" and also give rise to mistakes in other parsers

should href be fixed from the extension? Alternatively should the href be checked/extrated from the html provided in tktrex/htmls?

![image](https://user-images.githubusercontent.com/28983363/141066447-688c9ae9-3596-4852-9a92-8dd6296af03d.png)

**Comment by vecna** [comment]
where you see the "unmanaged condition" debug message https://github.com/tracking-exposed/tktrex/blob/main/backend/parsers/nature.js#L31 is it should manage by extending the parser

**Comment by rugantio** [comment]
in this case the "unmanaged condition" is triggered by the href "https://www.tiktok.com/@edsheeran?lang=en" 
my question is, should I assume this href to be reliable/correct and build nature.js according to it? (atm it is not, it only returns "foryou" or a tiktok account in my trials)
alternatively: should I bypass the href field and try to extract this information from the html field?
