### ISSUE TITLE
other htmls?

### ISSUE THREAD

**Issue by rugantio** [tracking-exposed/tktrex#5]
Atm I am unable to retrieve different htmls from different sources (tags, searches), if anyone could provide some snippets I can test the parsers that I wrote for the "foryou"

**Comment by cramdoulfa** [comment]
[mongo_records.zip](https://github.com/tracking-exposed/tktrex/files/7565435/mongo_records.zip)
Here are some htmls collected from TkTrex on my browser
There are 2 jsons:
- one from a 'search' page. Looks like the extension was responsive to 'load more' and collected 14 videos
- one from the for_you page. Looks like the extension only collected the first video.

**Comment by rugantio** [comment]
I pushed two different (but similar) python-based parsers for the two different files - they needed to be handled a bit differently. 
Located in the backend/parsers dir on the dev branch. They take the json as input and spit a csv as output. You can use them as such:
```
$ python ../foryou_parser.py -i="./mongo_htmls_foryou.json" -o="./mongo_htmls_foryou.csv"
$ python ../mysearch_parser.py -i="./mongo_htmls_search.json" -o="./mongo_htmls_search.csv"
```
Both htmls are lacking data that we would be interested in parsing. The extension needs to be corrected
- foryou is missing: text (and tags), shares, likes, comments, date 
- search is missing: shares, likes, comments, date

I will be porting these scripts to js, so that I can update directly the mongodb instead of producing a csv
